import type { Cost, GameState, UpgradeId } from '../types'

export type UpgradeEffect =
  | { target: 'click'; multiplier: number }
  | { target: 'drone' | 'excavator' | 'laser'; multiplier: number }
  | { target: 'smelter' | 'factory' | 'neurolab'; input: number; output: number }
  | { target: 'global'; multiplier: number }
  | { target: 'special' }

export interface UpgradeDef {
  id: UpgradeId
  name: string
  description: string
  effect: UpgradeEffect
  cost: Cost
  requirement: string
  isUnlocked: (state: GameState) => boolean
}

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'click1',
    name: 'Алмазные буры',
    description: 'Бьёшь вдвое сильнее',
    effect: { target: 'click', multiplier: 2 },
    cost: { ore: 50 },
    requirement: 'добыто 100 руды',
    isUnlocked: (s) => s.stats.totalProduced.ore >= 100,
  },
  {
    id: 'click2',
    name: 'Плазменный резак',
    description: 'Удар снова вдвое сильнее',
    effect: { target: 'click', multiplier: 2 },
    cost: { ore: 500 },
    requirement: '10 дронов',
    isUnlocked: (s) => s.buildings.drone >= 10,
  },
  {
    id: 'drone1',
    name: 'Автопилот дронов',
    description: 'Дроны копают вдвое быстрее',
    effect: { target: 'drone', multiplier: 2 },
    cost: { ore: 500 },
    requirement: '10 дронов',
    isUnlocked: (s) => s.buildings.drone >= 10,
  },
  {
    id: 'excavator1',
    name: 'Титановые ковши',
    description: 'Экскаваторы черпают вдвое больше',
    effect: { target: 'excavator', multiplier: 2 },
    cost: { ore: 2000 },
    requirement: '10 экскаваторов',
    isUnlocked: (s) => s.buildings.excavator >= 10,
  },
  {
    id: 'drone2',
    name: 'Рой дронов',
    description: 'Дроны снова вдвое быстрее',
    effect: { target: 'drone', multiplier: 2 },
    cost: { alloy: 200 },
    requirement: '25 дронов',
    isUnlocked: (s) => s.buildings.drone >= 25,
  },
  {
    id: 'smelter1',
    name: 'Плазменная печь',
    description: 'Плавильни жарят вдвое быстрее',
    effect: { target: 'smelter', input: 2, output: 2 },
    cost: { alloy: 300 },
    requirement: '10 плавилен',
    isUnlocked: (s) => s.buildings.smelter >= 10,
  },
  {
    id: 'excavator2',
    name: 'Автономные экскаваторы',
    description: 'Экскаваторы снова вдвое мощнее',
    effect: { target: 'excavator', multiplier: 2 },
    cost: { alloy: 1000 },
    requirement: '25 экскаваторов',
    isUnlocked: (s) => s.buildings.excavator >= 25,
  },
  {
    id: 'smelter2',
    name: 'Катализатор',
    description: 'Плавильни дают +50 % сплава, руды жгут столько же',
    effect: { target: 'smelter', input: 1, output: 1.5 },
    cost: { chip: 50 },
    requirement: '25 плавилен',
    isUnlocked: (s) => s.buildings.smelter >= 25,
  },
  {
    id: 'drone3',
    name: 'Дроны-репликаторы',
    description: 'Дроны копают ещё вдвое быстрее',
    effect: { target: 'drone', multiplier: 2 },
    cost: { chip: 100 },
    requirement: '50 дронов',
    isUnlocked: (s) => s.buildings.drone >= 50,
  },
  {
    id: 'factory1',
    name: 'Нанолитография',
    description: 'Фабрики печатают вдвое быстрее',
    effect: { target: 'factory', input: 2, output: 2 },
    cost: { chip: 100 },
    requirement: '10 фабрик',
    isUnlocked: (s) => s.buildings.factory >= 10,
  },
  {
    id: 'click3',
    name: 'Гравитационный захват',
    description: 'Удар втрое сильнее',
    effect: { target: 'click', multiplier: 3 },
    cost: { chip: 500 },
    requirement: '1 фабрика',
    isUnlocked: (s) => s.buildings.factory >= 1,
  },
  {
    id: 'factory2',
    name: 'Чистые комнаты',
    description: 'Фабрики дают +50 % чипов даром',
    effect: { target: 'factory', input: 1, output: 1.5 },
    cost: { chip: 1000 },
    requirement: '25 фабрик',
    isUnlocked: (s) => s.buildings.factory >= 25,
  },
  {
    id: 'laser1',
    name: 'Фокусировка',
    description: 'Лазеры бьют вдвое сильнее',
    effect: { target: 'laser', multiplier: 2 },
    cost: { chip: 5000 },
    requirement: '10 лазеров',
    isUnlocked: (s) => s.buildings.laser >= 10,
  },
  {
    id: 'global1',
    name: 'Тёмная энергия',
    description: 'Всё производство в полтора раза быстрее',
    effect: { target: 'global', multiplier: 1.5 },
    cost: { chip: 10000 },
    requirement: '1 перелёт',
    isUnlocked: (s) => s.prestigeCount >= 1,
  },
  {
    id: 'crowd',
    name: 'Эффект толпы',
    description: 'Каждый десятый удар — в десять раз жирнее',
    effect: { target: 'special' },
    cost: { ore: 5000 },
    requirement: '500 кликов',
    isUnlocked: (s) => s.stats.clicks >= 500,
  },
  {
    id: 'ionwind',
    name: 'Ионный ветер',
    description: 'Каждый экскаватор подгоняет дронов на 1 %',
    effect: { target: 'special' },
    cost: { alloy: 800 },
    requirement: '10 экскаваторов',
    isUnlocked: (s) => s.buildings.excavator >= 10,
  },
  {
    id: 'tailings',
    name: 'Переплавка хвостов',
    description: 'Плавильни не простаивают: четверть мощности всегда',
    effect: { target: 'special' },
    cost: { chip: 400 },
    requirement: '10 плавилен',
    isUnlocked: (s) => s.buildings.smelter >= 10,
  },
  {
    id: 'sling',
    name: 'Гравитационная праща',
    description: 'Пойманный метеор снимает 10 секунд с перезарядки перегрузки',
    effect: { target: 'special' },
    cost: { chip: 1500 },
    requirement: '10 пойманных метеоров',
    isUnlocked: (s) => s.stats.meteorsCaught >= 10,
  },
  {
    id: 'resonance',
    name: 'Рудный резонанс',
    description: 'Каждый удар подгоняет добытчиков на пятую долю секунды',
    effect: { target: 'special' },
    cost: { chip: 2000 },
    requirement: '25 дронов',
    isUnlocked: (s) => s.buildings.drone >= 25,
  },
  {
    id: 'crit1',
    name: 'Резонансный удар',
    description: 'Криты случаются вдвое чаще',
    effect: { target: 'special' },
    cost: { alloy: 1500 },
    requirement: '1 000 кликов',
    isUnlocked: (s) => s.stats.clicks >= 1_000,
  },
  {
    id: 'lab1',
    name: 'Параллельные вычисления',
    description: 'Лаборатории думают вдвое быстрее',
    effect: { target: 'neurolab', input: 2, output: 2 },
    cost: { core: 100 },
    requirement: '5 нейролабораторий',
    isUnlocked: (s) => s.buildings.neurolab >= 5,
  },
  {
    id: 'ai1',
    name: 'Предиктивная добыча',
    description: 'ИИ подсказывает, где копать: всё производство +50 %',
    effect: { target: 'global', multiplier: 1.5 },
    cost: { core: 200 },
    requirement: 'произведено 100 ядер',
    isUnlocked: (s) => s.stats.totalProduced.core >= 100,
  },
  {
    id: 'protocols',
    name: 'Протоколы ИИ',
    description: 'Открывает режимы работы базы',
    effect: { target: 'special' },
    cost: { core: 300 },
    requirement: '10 нейролабораторий',
    isUnlocked: (s) => s.buildings.neurolab >= 10,
  },
  {
    id: 'laser2',
    name: 'ИИ-наводка',
    description: 'Лазеры бьют втрое сильнее',
    effect: { target: 'laser', multiplier: 3 },
    cost: { core: 400 },
    requirement: '25 лазеров',
    isUnlocked: (s) => s.buildings.laser >= 25,
  },
  {
    id: 'click4',
    name: 'Оптимизатор кликов',
    description: 'Удар впятеро сильнее',
    effect: { target: 'click', multiplier: 5 },
    cost: { core: 600 },
    requirement: '10 000 кликов',
    isUnlocked: (s) => s.stats.clicks >= 10_000,
  },
  {
    id: 'factory3',
    name: 'Самосборка',
    description: 'Фабрики дают вдвое больше чипов даром',
    effect: { target: 'factory', input: 1, output: 2 },
    cost: { core: 1000 },
    requirement: '50 фабрик',
    isUnlocked: (s) => s.buildings.factory >= 50,
  },
  {
    id: 'smelter3',
    name: 'Квантовое сжатие',
    description: 'Плавильни жарят втрое быстрее',
    effect: { target: 'smelter', input: 3, output: 3 },
    cost: { core: 1500 },
    requirement: '50 плавилен',
    isUnlocked: (s) => s.buildings.smelter >= 50,
  },
  {
    id: 'dream',
    name: 'Сны машин',
    description: 'Лаборатории работают вполсилы даже без чипов',
    effect: { target: 'special' },
    cost: { core: 2500 },
    requirement: '25 нейролабораторий',
    isUnlocked: (s) => s.buildings.neurolab >= 25,
  },
  {
    id: 'ai2',
    name: 'Сверхразум',
    description: 'Всё производство вдвое быстрее',
    effect: { target: 'global', multiplier: 2 },
    cost: { core: 5000 },
    requirement: 'произведено 10 000 ядер',
    isUnlocked: (s) => s.stats.totalProduced.core >= 10_000,
  },
  {
    id: 'singularity',
    name: 'Сингулярность',
    description: 'Ядра сильнее разгоняют награду за перелёт',
    effect: { target: 'special' },
    cost: { core: 10_000 },
    requirement: '3 перелёта',
    isUnlocked: (s) => s.prestigeCount >= 3,
  },
]

export const upgradeDef = (id: UpgradeId): UpgradeDef => UPGRADES.find((u) => u.id === id)!

export const availableUpgrades = (state: GameState): UpgradeDef[] =>
  UPGRADES.filter((u) => !state.upgrades.includes(u.id) && u.isUnlocked(state))
